version: "3.8"
services:

  app:
    build:
      context: .
      dockerfile: ./docker/app.Dockerfile
    working_dir: /app
    env_file: .env
    restart: always
    expose:
      - "9000"

  nginx:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    restart: always
    depends_on:
      - app
    ports:
      - "8080:80"
    networks:
      - default
